export default {
  index: "Windows Phone React",
  installation: "Installation",
  theme: "Theme and tokens",
  motion: "Motion principles",
  "accessibility-support": "Accessibility and support",
  composition: "Composition patterns",
  tiles: "Tiles and grid",
  "reveal-tile": "RevealTile",
  "live-tile": "LiveTile",
  pressable: "Pressable",
  buttons: "Button and IconButton",
  "app-bar": "AppBar and overflow",
  transition: "Transition and Stagger",
  pivot: "Pivot",
  panorama: "Panorama",
  "tile-sequence": "TileSequence",
  "progress-dots": "ProgressDots",
  fields: "Fields and text input",
  "select-slider": "Select and Slider",
  selection: "Checkbox, Switch and RadioGroup",
  progress: "Progress and ProgressRing",
  "message-banner": "MessageBanner",
  dialog: "Dialog and AlertDialog",
  floating: "Menu and Popover",
  list: "Lists and empty states",
};
